// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv"
import { defineConfig, env } from "prisma/config"

dotenv.config({
  path: ".env.local",
  override: true,
  debug: false,
  quiet: true,
})

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // engine: "classic",
  datasource: {
    url: process.env["EXPRESS_PUBLIC_SUPABASE_DIRECT_URL"],
  },
})
